[manifest]
version = "1.0.0"
dump_lua = true
priority = 99

# If we're in the Student Loan Debt Challenge, put ourselves deep in debt
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
elseif v.id == 'no_shop_jokers' then 
    self.GAME.joker_rate = 0
'''
position = "after"
payload = '''
elseif v.id == 'go_deep_into_debt' then 
    self.GAME.bankrupt_at = -300
'''
match_indent = true
